info:
  author: greboreda
  app-name: portal

server:
  port: 8080
  servlet:
#    path: /${info.app-name}

spring:
  application:
    name: ${info.app-name}
  main:
    banner-mode: console
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.greboreda.portal.config.LowerCasePhysicalNamingStrategy
        #physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
